apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values - zastąp właściwymi wartościami
  secret-key: "your-base64-encoded-secret-key"
  database-url: "your-base64-encoded-database-url"
  redis-url: "your-base64-encoded-redis-url"