# django-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: default
  labels:
    app: django-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: django-app

---
# django-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: default
data:
  aws-region: "eu-central-1"
  s3-bucket-name: "django-app-dev-static-files"
  environment: "dev"
  log-level: "INFO"